FIX: broken specs
Since https://github.com/discourse/discourse/commit/92312eec7b14b421b872b0f20d6f3363c9e92fd6 this theme has been broken with the following error:

```
TypeError: s.default.reopen is not a function
```

Removing all these reopen, all the tests pass. Im also wondering if we still need this in core (app/assets/javascripts/discourse/app/components/category-title-link.gjs):

```
// icon name defined on prototype so it can be easily overridden in theme components
CategoryTitleLink.prototype.lockIcon = "lock";
```

It doesn’t seem to be used anywhere.